In [1]:
import numpy as np
from sklearn import datasets

iris = datasets.load_iris()

#### 1. Carregar “data” i "target" del conjunt de dades, i visualitza els 10 primers registres de cadascun.

In [2]:
data = iris.data
target = iris.target

print("Primers 10 registres de 'data':\n", data[:10])
print("\nPrimers 10 registres de 'target':\n", target[:10])

Primers 10 registres de 'data':
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]

Primers 10 registres de 'target':
 [0 0 0 0 0 0 0 0 0 0]


#### 2. Concatena “data” i “target” en un nou array. Mostra els 5 primers registres.

In [4]:
data_target = np.column_stack((data, target))

print('Primers 5 registres del nou array:\n', data_target[:5])

Primers 5 registres del nou array:
 [[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


#### 3. Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.

In [9]:
print('Mitjana de la longitud del sèpal: ' + str(round(np.mean(data_target[:, 0]), 2)) + ' cm.')
print('Desviació estàndar de la longitud del sèpal: ' + str(round(np.std(data_target[:, 0]), 2)) + ' cm.')


Mitjana de la longitud del sèpal: 5.84 cm.
Desviació estàndar de la longitud del sèpal: 0.83 cm.


In [10]:
print('Mitjana de la longitud del pètal: ' + str(round(np.mean(data_target[:, 2]),2)) + 'cm.')
print('Desviació estàndar de la longitud del pètal: ' + str(round(np.std(data_target[:,2]),2)) +' cm.')

Mitjana de la longitud del pètal: 3.76cm.
Desviació estàndar de la longitud del pètal: 1.76 cm.


#### 4. Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.

In [11]:
from numpy import random

mostra_aleatoria = data_target[np.random.choice(data_target.shape[0], size=20, replace=False)]

print('Mostra aleatòria de 20 registres:\n', mostra_aleatoria)

Mostra aleatòria de 20 registres:
 [[6.3 3.3 4.7 1.6 1. ]
 [6.3 3.4 5.6 2.4 2. ]
 [6.  3.  4.8 1.8 2. ]
 [7.7 2.6 6.9 2.3 2. ]
 [4.6 3.2 1.4 0.2 0. ]
 [5.7 3.8 1.7 0.3 0. ]
 [5.  3.4 1.6 0.4 0. ]
 [6.3 2.5 5.  1.9 2. ]
 [5.1 3.3 1.7 0.5 0. ]
 [5.7 2.6 3.5 1.  1. ]
 [6.3 2.7 4.9 1.8 2. ]
 [6.  2.2 5.  1.5 2. ]
 [4.9 3.  1.4 0.2 0. ]
 [6.5 3.2 5.1 2.  2. ]
 [6.1 2.6 5.6 1.4 2. ]
 [5.  3.5 1.6 0.6 0. ]
 [4.8 3.4 1.6 0.2 0. ]
 [5.1 3.5 1.4 0.2 0. ]
 [6.9 3.1 5.1 2.3 2. ]
 [6.5 3.  5.2 2.  2. ]]


#### 5. Crea una matriu que mostri: 
- La mitjana de cada característica per espècie. 
- La desviació estàndard de cada característica per espècie.

In [12]:
especies = np.unique(iris['target'])

mitjanes_per_especie = []
desviacions_per_especie = []

for especie in especies:
    dades_especie = iris['data'][iris['target'] == especie, :]

    mitjanes = np.mean(dades_especie, axis=0)
    desviacions = np.std(dades_especie, axis=0)

    mitjanes_per_especie.append(mitjanes)
    desviacions_per_especie.append(desviacions)

mitjanes_per_especie = np.array(mitjanes_per_especie)
desviacions_per_especie = np.array(desviacions_per_especie)

print('Mitjanes per Característica i Espècie:\n', mitjanes_per_especie)
print('\nDesviacions Estàndard per Característica i Espècie:\n',desviacions_per_especie)

Mitjanes per Característica i Espècie:
 [[5.006 3.428 1.462 0.246]
 [5.936 2.77  4.26  1.326]
 [6.588 2.974 5.552 2.026]]

Desviacions Estàndard per Característica i Espècie:
 [[0.34894699 0.37525458 0.17191859 0.10432641]
 [0.51098337 0.31064449 0.46518813 0.19576517]
 [0.62948868 0.31925538 0.54634787 0.27188968]]


#### 6. 
- Calcula la quantitat de mostres per espècie.
- Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"

In [26]:
mostres_per_especie = np.bincount(iris['target'])

noms_especies = iris['target_names']

for especie, quantitat in np.ndenumerate(mostres_per_especie):
    nom_especie = noms_especies[especie]
    print(f'Espècie {nom_especie}: {quantitat} mostres')

Espècie setosa: 50 mostres
Espècie versicolor: 50 mostres
Espècie virginica: 50 mostres


In [27]:
max_longitud_sepal = np.argmax(mitjanes_per_especie[:, 0])

print(f"L'espècie amb el valor màxim de la mitjana de la variable 'sepal length (cm)' és: {noms_especies[max_longitud_sepal]}")

L'espècie amb el valor màxim de la mitjana de la variable 'sepal length (cm)' és: virginica


#### 7. 
- Calcula la matriu de correlació entre les variables.
- Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 
- Troba la mostra amb els pètals més grans.

In [28]:
matriu_correlacio = np.corrcoef(data, rowvar=False)
matriu_correlacio

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ]])

In [29]:
mitjana_longitud_petal = np.mean(data[:, 2])

valors_major_mitjana = data[data[:, 2] > mitjana_longitud_petal, 2]

print('Valors majors a la mitjana de la longitud dels pètals:\n', valors_major_mitjana)

Valors majors a la mitjana de la longitud dels pètals:
 [4.7 4.5 4.9 4.  4.6 4.5 4.7 4.6 3.9 4.2 4.  4.7 4.4 4.5 4.1 4.5 3.9 4.8
 4.  4.9 4.7 4.3 4.4 4.8 5.  4.5 3.8 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  4.2 4.2 4.2 4.3 4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 5.1
 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8 4.9 5.6
 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7 5.2 5.
 5.2 5.4 5.1]


In [30]:
max_longitud_petals = data[np.argmax(data[:,2])]

print('La mostra amb els pètals més grans és la següent:', max_longitud_petals)

La mostra amb els pètals més grans és la següent: [7.7 2.6 6.9 2.3]


#### 8. Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.

In [31]:
especie_dif_max = noms_especies[np.argmax(np.abs(mitjanes_per_especie[:, 0] - mitjanes_per_especie[:, 2]))]

print("L'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals és:", especie_dif_max)

L'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals és: setosa
